name: common ci main
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
jobs:
  Download-Dependencies:
    runs-on: [self-hosted]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: echo Build

  Test: 
    needs: Download-Dependencies
    runs-on: [self-hosted]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: echo Test

  DockerBuild-n-Push:
    runs-on: self-hosted
    needs: Test
    steps:
      - name: check out repo code
        uses: actions/checkout@v4
      - run: echo Test
      
  Dev-Deployment:
    needs: Test
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: thippareddyom/roboshop-helm
      - name:  Deploy  
        run: |
          export PATH=/home/github/.local/bin:/home/github/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
          aws eks update-kubeconfig --name dev
          helm upgrade -i ${{ inputs.component_name }} . -f env-dev/${{ inputs.component_name }}.yaml