name: common ci
on:
  workflow_call:
    inputs:
      component_name:
        required: true
        type: string
jobs:
  Build:
    runs-on: [self-hosted]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: echo Build

  Test: 
    needs: Build
    runs-on: [self-hosted]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: echo Test

  Dev-Deployment:
    needs: Test
    runs-on: self-hosted
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          repository: thippareddyom/roboshop-helm
      - name:  Deploy  
        run: helm upgrade -i ${{ inputs.component_name }} . -f env-dev/${{ inputs.component_name }}.yaml