name: common ci
on:
  [workflow_call]
jobs:
  Build:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: echo Build
  Test: 
    needs: Build
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: echo Test
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - run: echo deploy